services:

  grafana:
    image: grafana/grafana
    container_name: cloudpilot-grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus

  api:
    build:
      context: ./backend

    container_name: cloudpilot-api

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine

    container_name: cloudpilot-postgres

    environment:
      POSTGRES_USER: cloudpilot
      POSTGRES_PASSWORD: cloudpilot
      POSTGRES_DB: cloudpilot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

    container_name: cloudpilot-redis

    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus

    container_name: cloudpilot-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

    depends_on:
      - api

volumes:
  postgres_data:
  prometheus-data:
  grafana-data:
