apiVersion: v1
kind: Secret

metadata:
  name: cloudpilot-secret-helm

type: Opaque

stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
