name: CloudPilot CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Check Python Syntax
        run: |
          cd backend
          find app -name "*.py" -exec python -m py_compile {} \;

      - name: Build Docker Image
        run: |
             docker build -t cloudpilot-api ./backend
